server {
  listen 8080;
  client_max_body_size 100M;
  location = /reload-model { proxy_pass http://127.0.0.1:8001/reload-model; proxy_set_header Authorization $http_authorization; }
  location = /health { proxy_pass http://127.0.0.1:8001/health; }
  location / { proxy_pass http://127.0.0.1:8501; proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; }
}
